/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.dianrosapratama.latihanmvcjdbc.view;

import edu.dianrosapratama.latihanmvcjdbc.error.PelangganException;
import java.sql.SQLException;

/**
 *
 * @author user
 */
public class MainViewPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form MainViewPelanggan
     */
    public MainViewPelanggan() {
        initComponents();
        
    }

    public void loadDatabase() throws SQLException, PelangganException {
        pelanngganview1.loadDatabase();
    }

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelanngganview1 = new edu.dianrosapratama.latihanmvcjdbc.view.pelanngganview();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(pelanngganview1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.dianrosapratama.latihanmvcjdbc.view.pelanngganview pelanngganview1;
    // End of variables declaration//GEN-END:variables
}
